name: Android Pull Request

on:
  pull_request:
    branches:
      - develop
      - dev

jobs:
  test:
    name: Run Unit Tests
    env:
      REPO_USER_EMAIL: ${{ secrets.REPO_USER_EMAIL }}
      REPO_USER_NAME: ${{ secrets.REPO_USER_NAME }}
      APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN }}
      APP_CENTER_OWNER: ${{ secrets.APP_CENTER_OWNER }}
      APP_CENTER_APP_NAME: ${{ secrets.APP_CENTER_APP_NAME }}
      APP_CENTER_DESTINATIONS: ${{ secrets.APP_CENTER_DESTINATIONS }}
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: '13.0.2'

      - name: Fastlane install
        run: brew install fastlane

      - name: Bundle Install
        run: bundle install

      - name: Give permissions
        run: sh .github/scripts/give_permissions_gradle.sh

      - name: Update Fastlane
        run: bundle update fastlane

      - name: Run tests
        run: bundle exec fastlane build_and_test_debug
