name: Android Release

on:
  push:
    branches:
      - main
      - master

jobs:
  apk:
    name: Generate APK
    env:
      REPO_USER_EMAIL: ${{ secrets.REPO_USER_EMAIL }}
      REPO_USER_NAME: ${{ secrets.REPO_USER_NAME }}
      APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN }}
      APP_CENTER_OWNER: ${{ secrets.APP_CENTER_OWNER }}
      APP_CENTER_APP_NAME: ${{ secrets.APP_CENTER_APP_NAME }}
      APP_CENTER_DESTINATIONS: ${{ secrets.APP_CENTER_DESTINATIONS }}
    runs-on: macOS-latest


    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Fastlane install
        run: brew install fastlane

      - name: Give permissions
        run: sh .github/scripts/give_permissions_gradle.sh

      - name: Fetch Git tags
        run: sh .github/scripts/fetch_git_tags.sh

      - name: Bundle Install
        run: bundle install

      - name: Update Fastlane
        run: bundle update fastlane

      - name: Install increment version plugin
        run: bundle exec fastlane add_plugin increment_version_code

      - name: Install get version plugin
        run: bundle exec fastlane add_plugin get_version_code

      - name: Install appcenter plugin
        run: bundle exec fastlane add_plugin appcenter

      - name: Run Build, Tests and Deploy
        run: bundle exec fastlane deploy_app_to_appcenter
